### ISSUE TITLE
env: singularity: No such file or directory

### ISSUE THREAD

**Issue by erikstricker** [sdjebali/PaintorPipe#2]
Dear developers,
I have successfully run the PAINTORpipe workflow with my first dataset, and I am very happy with its smoothness. 

However, on Friday, 8/30/2024 2:54 pm CST, I received the following error with all my currently running datasets

`env: singularity: No such file or directory`

The error occurred at different steps for each dataset and now I cannot even get beyond step one.

Please help.

**Comment by erikstricker** [comment]
[paintorpipe.Heart_failure_MI_censor_age_sex_covar_jap_cardiomyo.out.txt](https://github.com/user-attachments/files/16853021/paintorpipe.Heart_failure_MI_censor_age_sex_covar_jap_cardiomyo.out.txt)
[paintorpipe.Heart_failure_MI_censor_age_sex_covar_jap_heartfail.out.txt](https://github.com/user-attachments/files/16853022/paintorpipe.Heart_failure_MI_censor_age_sex_covar_jap_heartfail.out.txt)
[paintorpipe.Heart_failure_MI_censor_age_sex_plus_covar_jap_cardiomyo.out.txt](https://github.com/user-attachments/files/16853023/paintorpipe.Heart_failure_MI_censor_age_sex_plus_covar_jap_cardiomyo.out.txt)
[paintorpipe.QT_intervals.out.txt](https://github.com/user-attachments/files/16853026/paintorpipe.QT_intervals.out.txt)

**Comment by erikstricker** [comment]
Issue resolved:

the `Singularity` file in the paintorpipe folder should be named `singularity` with lower case s

**Comment by sdjebali** [comment]
Thanks for using PaintorPipe and for pointing this issue
and also for solving it so quickly !
