### ISSUE TITLE
NA18498 in mapFile.txt but not in vcf files

### ISSUE THREAD

**Issue by erikstricker** [sdjebali/PaintorPipe#3]
I received the following error when running PAINTORpipe in with AFR as population

`Traceback (most recent call last):
  File "/usr/local/bin/CalcLD_1KG_VCF.py", line 268, in <module>
    if __name__ == "__main__": main()
  File "/usr/local/bin/CalcLD_1KG_VCF.py", line 263, in main
    pop_haps = Extract_Pop_Haps(final_reference, pop_ids)
  File "/usr/local/bin/CalcLD_1KG_VCF.py", line 84, in Extract_Pop_Haps
    extract_index = [header_str.index(ids) for ids in pop_ids]
  File "/usr/local/bin/CalcLD_1KG_VCF.py", line 84, in <listcomp>
    extract_index = [header_str.index(ids) for ids in pop_ids]
ValueError: 'NA18498' is not in list`

**Comment by sdjebali** [comment]
Thanks for your message. 

It appears this sample is present in the hg19 VCF files but not in the hg38 ones. 

Is it possible for you to share your inputs so that I can reproduce the problem and solve it? Or a small example from your data ?

Thanks

**Comment by erikstricker** [comment]
Here are my files:
[annotations_hg38_txt.txt](https://github.com/user-attachments/files/17382650/annotations_hg38_txt.txt)
[hg38_exons_sorted.txt](https://github.com/user-attachments/files/17382651/hg38_exons_sorted.txt)

[sorted_noindel_afr_recurrent_pregnancy_loss_w_6PCs_w_age_at_CDR_and_age_at_CDR_squared_paintorpipe_ready.GWAS_chr3.txt](https://github.com/user-attachments/files/17382628/sorted_noindel_afr_recurrent_pregnancy_loss_w_6PCs_w_age_at_CDR_and_age_at_CDR_squared_paintorpipe_ready.GWAS_chr3.txt)
[hg38_introns_sorted.txt](https://github.com/user-attachments/files/17382655/hg38_introns_sorted.txt)

**Comment by erikstricker** [comment]
And the script:
```
#!/bin/bash
#SBATCH --time=36:00:00
#SBATCH --mem-per-cpu=1024
#SBATCH --job-name=run_paintorpipe_grepl_afr
#SBATCH --output=run_paintorpipe_grepl_afr.%J.stdout
### mail on job exit
#SBATCH --mail-type=END
### email address to send job updates

module load anaconda3/2024.02
module load python/3.12.2
source activate base
conda activate paintorpipe_env 
export PATH=/storage/shared_software/software/nextflow:$PATH
export PATH=/usr/bin/singularity:$PATH
export PATH=/storage/paintorpipe/PAINTOR_V3.1:$PATH
export PATH=/storage/paintorpipe/PaintorPipe/Scripts:$PATH
module load java/jdk-21.0.2
module unload python
cd /storage/2_analyses
bash launch_gerpl_afr_gwas_finemapping.sh
```

```
#!/bin/bash

     mydir="/storage/3_results/PaintorPipe-gerpl_afr_gwas_run"
     codedir=/storage/paintorpipe/PaintorPipe
     singularity_image="/storage/paintorpipe/PaintorPipe/work/singularity/mainimage_0.1.sif"
     mkdir -p $mydir
     cd $mydir
     export PATH=/usr/bin/singularity:$PATH
     export PATH=/storage/paintorpipe/PAINTOR_V3.1:$PATH
     export PATH=/storage/paintorpipe/PaintorPipe/Scripts:$PATH
     
     module load java/jdk-21.0.2
     nextflow -C $codedir/nextflow.config \
    run $codedir/main.nf \
    -config $codedir/nextflow.config,$codedir/genologin.config, \
    --gwasFile /storage/1_data/GERPL_GWAS_6PCs_and_age_covars/sorted_noindel_afr_recurrent_pregnancy_loss_w_6PCs_w_age_at_CDR_and_age_at_CDR_squared_paintorpipe_ready.GWAS_chr3.txt \
    --annotationsFile $codedir/data/input/annotations_gerpl_gei_gwas_hg38.txt \
    --ref_genome hg38 \
    --pvalue_lead 5e-08 \
    --kb 500 \
    --snp 100000 \
    --pp_threshold 0.001 \
    --population AFR \
    -profile slurm,singularity \
    -with-singularity $singularity_image \
    -with-trace reports/trace.txt \
    -with-timeline reports/timeline.html \
    -with-report reports/report.html \
    -with-dag reports/flowchart.png \
    -resume > $mydir/paintorpipe.gerpl_afr_gwas.out
```

**Comment by sdjebali** [comment]
Thanks a lot for the inputs and scripts, and more generally for your interest in PaintorPipe.

I indeed managed to reproduce your error and made a new code to solve it

Could you try with the latest code and tell me if it works ? in case it does I will make a new version

Best,

**Comment by sdjebali** [comment]
OK I made the new release 2.3 and I will close the issue

**Comment by sdjebali** [comment]
OK I made release 2.3 and I will close the issue
